"""Add plan support

Revision ID: 642ffea662e0
Revises: e34365690e1f
Create Date: 2025-10-09 17:44:33.222595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642ffea662e0'
down_revision = 'e34365690e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('option1', sa.String(length=255), nullable=True),
    sa.Column('option2', sa.String(length=255), nullable=True),
    sa.Column('option3', sa.String(length=255), nullable=True),
    sa.Column('option4', sa.String(length=255), nullable=True),
    sa.Column('option5', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_subscribed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        #batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])
        batch_op.drop_constraint('fk_user_plan_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('plan_subscribed_at')
        batch_op.drop_column('plan_id')

    op.drop_table('plan')
    # ### end Alembic commands ###
